#include "typecheck.hpp"

#include "instrument.hpp"

#include <utility>

namespace calliope::types {

using namespace calliope::ast;

namespace {

// ---- type construction --------------------------------------------------
TypeId new_var(Ctx& c) {
    int v = static_cast<int>(c.binding.size());
    c.binding.push_back(NoType);
    TypeNode n;
    n.is_var = true;
    n.var = v;
    c.pool.push_back(std::move(n));
    return static_cast<TypeId>(c.pool.size() - 1);
}

TypeId new_con(Ctx& c, std::string name, std::vector<TypeId> args) {
    TypeNode n;
    n.con = std::move(name);
    n.args = std::move(args);
    c.pool.push_back(std::move(n));
    return static_cast<TypeId>(c.pool.size() - 1);
}

TypeId t_con0(Ctx& c, const char* name) { return new_con(c, name, {}); }
TypeId t_arrow(Ctx& c, TypeId a, TypeId b) { return new_con(c, "->", {a, b}); }
TypeId t_list(Ctx& c, TypeId a) { return new_con(c, "List", {a}); }

TypeId resolve(Ctx& c, TypeId t) {
    for (;;) {
        const TypeNode& n = c.pool[t];
        if (n.is_var && c.binding[n.var] != NoType) { t = c.binding[n.var]; continue; }
        return t;
    }
}

bool occurs(Ctx& c, int var, TypeId t) {
    t = resolve(c, t);
    const TypeNode& n = c.pool[t];
    if (n.is_var) return n.var == var;
    for (TypeId a : n.args)
        if (occurs(c, var, a)) return true;
    return false;
}

// ---- environment --------------------------------------------------------
struct EnvEntry {
    std::string name;
    Scheme scheme;
};
using Env = std::vector<EnvEntry>;

// ---- checker state ------------------------------------------------------
struct ClassInfo {
    std::string name;
    std::string var;                 // the single class type variable name
    std::vector<std::string> methods;
};

struct Checker {
    const ast::Ast* ast = nullptr;
    Ctx ctx;
    std::vector<std::string>* errors = nullptr;
    std::vector<ClassInfo> classes;
    // declared instances: (class name, type constructor name)
    std::vector<std::pair<std::string, std::string>> instances;
    // constraints generated by method use, awaiting resolution: (class, type var)
    std::vector<std::pair<std::string, TypeId>> pending;
};

bool has_instance(const Checker& ck, const std::string& cls, const std::string& con) {
    for (const auto& kv : ck.instances)
        if (kv.first == cls && kv.second == con) return true;
    return false;
}

void fail(Checker& ck, const std::string& msg) {
    if (ck.errors) ck.errors->push_back(msg);
}

bool unify(Checker& ck, TypeId a, TypeId b) {
    Ctx& c = ck.ctx;
    a = resolve(c, a);
    b = resolve(c, b);
    if (a == b) return true;
    TypeNode na = c.pool[a];
    TypeNode nb = c.pool[b];
    if (na.is_var) {
        if (occurs(c, na.var, b)) { fail(ck, "infinite type"); return false; }
        c.binding[na.var] = b;
        return true;
    }
    if (nb.is_var) {
        if (occurs(c, nb.var, a)) { fail(ck, "infinite type"); return false; }
        c.binding[nb.var] = a;
        return true;
    }
    if (na.con != nb.con || na.args.size() != nb.args.size()) {
        fail(ck, "type mismatch: " + na.con + " vs " + nb.con);
        return false;
    }
    bool ok = true;
    for (std::size_t i = 0; i < na.args.size(); i++)
        ok = unify(ck, na.args[i], nb.args[i]) && ok;
    return ok;
}

// ---- free variables, generalization, instantiation ----------------------
void free_vars(Ctx& c, TypeId t, std::vector<int>& out) {
    t = resolve(c, t);
    const TypeNode& n = c.pool[t];
    if (n.is_var) {
        for (int v : out) if (v == n.var) return;
        out.push_back(n.var);
        return;
    }
    for (TypeId a : n.args) free_vars(c, a, out);
}

TypeId inst_copy(Ctx& c, TypeId t, std::vector<std::pair<int, TypeId>>& m) {
    t = resolve(c, t);
    const TypeNode& n = c.pool[t];
    if (n.is_var) {
        for (auto& kv : m) if (kv.first == n.var) return kv.second;
        return t; // free var: shared
    }
    std::vector<TypeId> args;
    std::vector<TypeId> src = n.args; // copy: pool may reallocate during recursion
    for (TypeId a : src) args.push_back(inst_copy(c, a, m));
    std::string name = c.pool[t].con;
    return new_con(c, name, args);
}

TypeId instantiate(Checker& ck, const Scheme& s) {
    Ctx& c = ck.ctx;
    if (s.vars.empty() && s.constraints.empty()) return s.type;
    std::vector<std::pair<int, TypeId>> m;
    for (int v : s.vars) m.emplace_back(v, new_var(c));
    TypeId t = inst_copy(c, s.type, m);
    // each class constraint follows its variable to the fresh instance var,
    // becoming a pending obligation resolved once that var is grounded.
    for (const auto& con : s.constraints) {
        for (auto& kv : m)
            if (kv.first == con.second) { ck.pending.emplace_back(con.first, kv.second); break; }
    }
    return t;
}

bool env_find(const Env& env, std::string_view name, Scheme& out) {
    for (std::size_t i = env.size(); i-- > 0;) {
        if (env[i].name == name) { out = env[i].scheme; return true; }
    }
    return false;
}

// ---- inference ----------------------------------------------------------
bool is_interval_name(std::string_view s) {
    static const char* names[] = {
        "P1", "m2", "M2", "m3", "M3", "P4", "A4", "d5", "P5", "m6",
        "M6", "m7", "M7", "P8",
    };
    for (const char* n : names) if (s == n) return true;
    return false;
}

TypeId infer(Checker& ck, Env& env, NodeId id);

// Infer a pattern's type, pushing any pattern-variable bindings onto `env`
// (the caller resizes `env` back after the alternative's body).
TypeId infer_pattern(Checker& ck, Env& env, NodeId patId) {
    Ctx& c = ck.ctx;
    const Node& pat = ck.ast->nodes[patId];
    switch (pat.kind) {
        case NodeKind::PatWild: return new_var(c);
        case NodeKind::PatVar: {
            TypeId pv = new_var(c);
            Scheme s; s.type = pv;
            env.push_back({std::string(pat.tok.text), s});
            return pv;
        }
        case NodeKind::PatInt: return t_con0(c, "Int");
        case NodeKind::PatCon: {
            std::string_view name = pat.tok.text;
            if (name == "True" || name == "False") return t_con0(c, "Bool");
            if (name == "[") return t_list(c, new_var(c));   // empty list
            if (name == ":") {
                TypeId h = infer_pattern(ck, env, pat.kids[0]);
                TypeId t = infer_pattern(ck, env, pat.kids[1]);
                unify(ck, t, t_list(c, h));
                return t_list(c, h);
            }
            return new_var(c); // unknown constructor
        }
        default: return new_var(c);
    }
}

// operator type for a BinOp token; returns NoType if unknown
TypeId operator_type(Checker& ck, Env& env, std::string_view op) {
    Scheme s;
    if (env_find(env, op, s)) return instantiate(ck, s);
    return NoType;
}

TypeId infer(Checker& ck, Env& env, NodeId id) {
    Ctx& c = ck.ctx;
    const Node& n = ck.ast->nodes[id];
    switch (n.kind) {
        case NodeKind::IntLit:  return t_con0(c, "Int");
        case NodeKind::StrLit:  return t_con0(c, "Str");
        case NodeKind::PitchLit:return t_con0(c, "Pitch");
        case NodeKind::RestLit: return t_con0(c, "Music");
        case NodeKind::Seq:
        case NodeKind::Chord:
            for (NodeId k : n.kids) infer(ck, env, k);
            return t_con0(c, "Music");
        case NodeKind::Con:
            if (n.tok.text == "True" || n.tok.text == "False") return t_con0(c, "Bool");
            if (is_interval_name(n.tok.text)) return t_con0(c, "Interval");
            if (instrument::id_of(n.tok.text) >= 0) return t_con0(c, "Instrument");
            return new_var(c); // unknown constructor: leave open (WIP)
        case NodeKind::Var: {
            Scheme s;
            if (env_find(env, n.tok.text, s)) return instantiate(ck, s);
            fail(ck, "unbound name in type check: " + std::string(n.tok.text));
            return new_var(c);
        }
        case NodeKind::App: {
            TypeId tf = infer(ck, env, n.kids[0]);
            for (std::size_t k = 1; k < n.kids.size(); k++) {
                TypeId targ = infer(ck, env, n.kids[k]);
                TypeId res = new_var(c);
                unify(ck, tf, t_arrow(c, targ, res));
                tf = resolve(c, res);
            }
            return tf;
        }
        case NodeKind::BinOp: {
            TypeId top = operator_type(ck, env, n.tok.text);
            if (top == NoType) {
                fail(ck, "unknown operator in type check: " + std::string(n.tok.text));
                return new_var(c);
            }
            TypeId tl = infer(ck, env, n.kids[0]);
            TypeId tr = infer(ck, env, n.kids[1]);
            TypeId res = new_var(c);
            unify(ck, top, t_arrow(c, tl, t_arrow(c, tr, res)));
            return resolve(c, res);
        }
        case NodeKind::If: {
            TypeId tc = infer(ck, env, n.kids[0]);
            unify(ck, tc, t_con0(c, "Bool"));
            TypeId tt = infer(ck, env, n.kids[1]);
            TypeId te = infer(ck, env, n.kids[2]);
            unify(ck, tt, te);
            return resolve(c, tt);
        }
        case NodeKind::Case: {
            TypeId scrutT = infer(ck, env, n.kids[0]);
            TypeId resultT = new_var(c);
            for (std::size_t k = 1; k < n.kids.size(); k++) {
                const Node& alt = ck.ast->nodes[n.kids[k]];
                std::size_t base = env.size();
                TypeId patT = infer_pattern(ck, env, alt.kids[0]);
                unify(ck, scrutT, patT);
                TypeId bodyT = infer(ck, env, alt.kids[1]);
                unify(ck, resultT, bodyT);
                env.resize(base);
            }
            return resolve(c, resultT);
        }
        case NodeKind::ListLit: {
            TypeId el = new_var(c);
            for (NodeId k : n.kids) unify(ck, el, infer(ck, env, k));
            return t_list(c, el);
        }
        case NodeKind::Lambda: {
            std::size_t base = env.size();
            std::vector<TypeId> ptypes;
            for (int k = 0; k < n.extra; k++) {
                TypeId pv = new_var(c);
                ptypes.push_back(pv);
                Scheme s; s.type = pv;
                env.push_back({std::string(ck.ast->nodes[n.kids[k]].tok.text), s});
            }
            TypeId tbody = infer(ck, env, n.kids[n.extra]);
            env.resize(base);
            TypeId t = tbody;
            for (std::size_t k = ptypes.size(); k-- > 0;) t = t_arrow(c, ptypes[k], t);
            return t;
        }
        case NodeKind::Let: {
            std::size_t base = env.size();
            int nb = n.extra;
            // monomorphic let bindings (generalization is WIP; top-level only)
            for (int k = 0; k < nb; k++) {
                const Node& b = ck.ast->nodes[n.kids[k]];
                TypeId pv = new_var(c);
                Scheme s; s.type = pv;
                env.push_back({std::string(b.tok.text), s});
            }
            for (int k = 0; k < nb; k++) {
                const Node& b = ck.ast->nodes[n.kids[k]];
                // build a lambda-like type for function bindings
                std::size_t lbase = env.size();
                std::vector<TypeId> ptypes;
                for (int pp = 0; pp < b.extra; pp++) {
                    TypeId pv = new_var(c);
                    ptypes.push_back(pv);
                    Scheme s; s.type = pv;
                    env.push_back({std::string(ck.ast->nodes[b.kids[pp]].tok.text), s});
                }
                TypeId tbody = infer(ck, env, b.kids[b.extra]);
                env.resize(lbase);
                TypeId t = tbody;
                for (std::size_t pp = ptypes.size(); pp-- > 0;) t = t_arrow(c, ptypes[pp], t);
                Scheme bs;
                if (env_find(env, b.tok.text, bs)) unify(ck, bs.type, t);
            }
            TypeId tbody = infer(ck, env, n.kids[nb]);
            env.resize(base);
            return resolve(c, tbody);
        }
        default:
            return new_var(c);
    }
}

// ---- mini type-expression parser (for method signatures) ----------------
// Turns a MethodSig's raw TypeAtom tokens into a TypeId. Grammar:
//   type  := atype ('->' type)?            (arrows, right-associative)
//   atype := Upper | Ident | '[' type ']' | '(' type ')'
// Lowercase names are type variables (shared by name within one signature);
// uppercase names are nullary type constructors (Int, Pitch, Interval, Music…).
struct TypeParse {
    Checker* ck;
    const std::vector<NodeId>* atoms;
    std::size_t pos;
    std::vector<std::pair<std::string, TypeId>>* vars;
};

const Token& tp_cur(TypeParse& tp) {
    static const Token kEnd{};
    if (tp.pos >= tp.atoms->size()) return kEnd;
    return tp.ck->ast->nodes[(*tp.atoms)[tp.pos]].tok;
}
void tp_adv(TypeParse& tp) { if (tp.pos < tp.atoms->size()) tp.pos++; }

TypeId tp_lookup_var(TypeParse& tp, std::string_view name) {
    for (auto& kv : *tp.vars) if (kv.first == name) return kv.second;
    TypeId t = new_var(tp.ck->ctx);
    tp.vars->emplace_back(std::string(name), t);
    return t;
}

TypeId tp_type(TypeParse& tp);

TypeId tp_atype(TypeParse& tp) {
    const Token& t = tp_cur(tp);
    if (t.kind == TokenKind::LParen) {
        tp_adv(tp);
        TypeId inner = tp_type(tp);
        if (tp_cur(tp).kind == TokenKind::RParen) tp_adv(tp);
        return inner;
    }
    if (t.kind == TokenKind::LBracket) {
        tp_adv(tp);
        TypeId inner = tp_type(tp);
        if (tp_cur(tp).kind == TokenKind::RBracket) tp_adv(tp);
        return t_list(tp.ck->ctx, inner);
    }
    if (t.kind == TokenKind::Upper) {
        std::string name(t.text);
        tp_adv(tp);
        return t_con0(tp.ck->ctx, name.c_str());
    }
    if (t.kind == TokenKind::Ident) {
        std::string name(t.text);
        tp_adv(tp);
        return tp_lookup_var(tp, name);
    }
    if (tp.pos < tp.atoms->size()) tp_adv(tp);
    return new_var(tp.ck->ctx);
}

TypeId tp_type(TypeParse& tp) {
    TypeId left = tp_atype(tp);
    if (tp_cur(tp).kind == TokenKind::Arrow) {
        tp_adv(tp);
        return t_arrow(tp.ck->ctx, left, tp_type(tp));
    }
    return left;
}

// Build a qualified scheme `Cls clsVar => <sig>` for one class method.
Scheme method_scheme(Checker& ck, const Node& sig, const std::string& cls,
                     const std::string& clsVar) {
    std::vector<std::pair<std::string, TypeId>> vars;
    TypeId clsT = new_var(ck.ctx);
    vars.emplace_back(clsVar, clsT);
    TypeParse tp{&ck, &sig.kids, 0, &vars};
    TypeId t = tp_type(tp);
    Scheme s;
    s.type = t;
    for (auto& kv : vars) {
        TypeId r = resolve(ck.ctx, kv.second);
        if (ck.ctx.pool[r].is_var) s.vars.push_back(ck.ctx.pool[r].var);
    }
    int clsVarNum = ck.ctx.pool[resolve(ck.ctx, clsT)].var;
    s.constraints.emplace_back(cls, clsVarNum);
    return s;
}

// ---- class / instance declarations --------------------------------------
void register_classes(Checker& ck, Env& env) {
    if (ck.ast->root == ast::NoNode) return;
    const Node& prog = ck.ast->nodes[ck.ast->root];
    for (NodeId d : prog.kids) {
        const Node& cd = ck.ast->nodes[d];
        if (cd.kind != NodeKind::ClassDecl) continue;
        ClassInfo ci;
        ci.name = std::string(cd.tok.text);
        if (!cd.kids.empty()) ci.var = std::string(ck.ast->nodes[cd.kids[0]].tok.text);
        for (std::size_t i = 1; i < cd.kids.size(); i++) {
            const Node& sig = ck.ast->nodes[cd.kids[i]];
            std::string mname(sig.tok.text);
            ci.methods.push_back(mname);
            env.push_back({mname, method_scheme(ck, sig, ci.name, ci.var)});
        }
        ck.classes.push_back(std::move(ci));
    }
}

void register_instances(Checker& ck) {
    if (ck.ast->root == ast::NoNode) return;
    const Node& prog = ck.ast->nodes[ck.ast->root];
    for (NodeId d : prog.kids) {
        const Node& inst = ck.ast->nodes[d];
        if (inst.kind != NodeKind::InstanceDecl) continue;
        std::string cls(inst.tok.text);
        std::string ty(ck.ast->nodes[inst.kids[0]].tok.text);
        ck.instances.emplace_back(cls, ty);
    }
}

TypeId infer_binding(Checker& ck, Env& env, const Node& b);

// Validate each instance's method impls against the class method signatures.
void check_instances(Checker& ck, Env& env) {
    if (ck.ast->root == ast::NoNode) return;
    const Node& prog = ck.ast->nodes[ck.ast->root];
    for (NodeId d : prog.kids) {
        const Node& inst = ck.ast->nodes[d];
        if (inst.kind != NodeKind::InstanceDecl) continue;
        std::string cls(inst.tok.text);
        bool known = false;
        for (const ClassInfo& ci : ck.classes) if (ci.name == cls) { known = true; break; }
        if (!known) { fail(ck, "instance of unknown class: " + cls); continue; }
        for (std::size_t i = 1; i < inst.kids.size(); i++) {
            const Node& b = ck.ast->nodes[inst.kids[i]];
            std::string mname(b.tok.text);
            Scheme ms;
            if (!env_find(env, mname, ms)) {
                fail(ck, "instance method not declared by class " + cls + ": " + mname);
                continue;
            }
            TypeId tImpl = infer_binding(ck, env, b);
            TypeId tSig = instantiate(ck, ms);
            unify(ck, tImpl, tSig);
        }
    }
}

// Resolve pending class constraints: a grounded type must have an instance.
void resolve_constraints(Checker& ck) {
    for (auto& pc : ck.pending) {
        TypeId r = resolve(ck.ctx, pc.second);
        const TypeNode& n = ck.ctx.pool[r];
        if (n.is_var) continue; // still polymorphic: captured by a scheme or ambiguous
        if (!has_instance(ck, pc.first, n.con))
            fail(ck, "no instance for " + pc.first + " " + n.con);
    }
}

// Build the base environment of builtin operator/function types.
void seed_builtins(Checker& ck, Env& env) {
    Ctx& c = ck.ctx;
    auto add_mono = [&](const char* name, TypeId t) {
        Scheme s; s.type = t; env.push_back({name, s});
    };
    TypeId Int = t_con0(c, "Int");
    TypeId Bool = t_con0(c, "Bool");
    TypeId Pitch = t_con0(c, "Pitch");
    TypeId Interval = t_con0(c, "Interval");
    auto iii = [&]() { return t_arrow(c, t_con0(c, "Int"), t_arrow(c, t_con0(c, "Int"), t_con0(c, "Int"))); };
    add_mono("+", iii());
    add_mono("-", iii());
    add_mono("*", iii());
    add_mono("/", iii());
    // ordering is a builtin single-parameter class Ord (instances Int and Pitch;
    // pitches order by height / semitones). Music has no order — comparing two
    // phrases with `<` is a `no instance for Ord Music` error.
    //   (<), (>), (<=), (>=) :: Ord t => t -> t -> Bool
    for (const char* op : {"<", ">", "<=", ">="}) {
        TypeId a = new_var(c); int av = c.pool[a].var;
        Scheme s;
        s.vars.push_back(av);
        s.type = t_arrow(c, a, t_arrow(c, a, t_con0(c, "Bool")));
        s.constraints.emplace_back("Ord", av);
        env.push_back({op, s});
    }
    ck.classes.push_back({"Ord", "a", {"<", ">", "<=", ">="}});
    ck.instances.emplace_back("Ord", "Int");
    ck.instances.emplace_back("Ord", "Pitch");
    // equality: forall a. a -> a -> Bool
    {
        TypeId a = new_var(c);
        Scheme s; s.vars.push_back(c.pool[a].var);
        s.type = t_arrow(c, a, t_arrow(c, a, t_con0(c, "Bool")));
        env.push_back({"==", s});
        Scheme s2 = s; env.push_back({"/=", s2});
    }
    // boolean operators / function
    add_mono("and", t_arrow(c, t_con0(c, "Bool"), t_arrow(c, t_con0(c, "Bool"), t_con0(c, "Bool"))));
    add_mono("or",  t_arrow(c, t_con0(c, "Bool"), t_arrow(c, t_con0(c, "Bool"), t_con0(c, "Bool"))));
    add_mono("not", t_arrow(c, t_con0(c, "Bool"), t_con0(c, "Bool")));
    // Transposable is a real (builtin) single-parameter class with a builtin
    // instance for Pitch; user code may add more instances (e.g. Music).
    //   (^+), (^-) :: Transposable a => a -> Interval -> a
    for (const char* op : {"^+", "^-"}) {
        TypeId a = new_var(c);
        int av = c.pool[a].var;
        Scheme s;
        s.vars.push_back(av);
        s.type = t_arrow(c, a, t_arrow(c, Interval, a));
        s.constraints.emplace_back("Transposable", av);
        env.push_back({op, s});
    }
    ck.classes.push_back({"Transposable", "a", {"^+", "^-"}});
    ck.instances.emplace_back("Transposable", "Pitch");
    ck.instances.emplace_back("Transposable", "Music");
    // Phrase is a builtin single-parameter class: the things `:+:` / `:=:`
    // compose. Instances Pitch and Music, so a bare pitch lifts to a one-note
    // phrase (eval turns it into a note). The two operands may differ
    // (`c :+: (d e)` is Pitch :+: Music), so each side is independently
    // constrained and the result is always Music.
    //   (:+:), (:=:) :: Phrase t => Phrase u => t -> u -> Music
    for (const char* op : {":+:", ":=:"}) {
        TypeId a = new_var(c); int av = c.pool[a].var;
        TypeId b = new_var(c); int bv = c.pool[b].var;
        Scheme s;
        s.vars.push_back(av);
        s.vars.push_back(bv);
        s.type = t_arrow(c, a, t_arrow(c, b, t_con0(c, "Music")));
        s.constraints.emplace_back("Phrase", av);
        s.constraints.emplace_back("Phrase", bv);
        env.push_back({op, s});
    }
    ck.classes.push_back({"Phrase", "a", {":+:", ":=:"}});
    ck.instances.emplace_back("Phrase", "Pitch");
    ck.instances.emplace_back("Phrase", "Music");
    // `:*:` repeats a phrase n times in a row:  phrase :*: n
    //   (:*:) :: Phrase t => t -> Int -> Music
    {
        TypeId a = new_var(c); int av = c.pool[a].var;
        Scheme s;
        s.vars.push_back(av);
        s.type = t_arrow(c, a, t_arrow(c, t_con0(c, "Int"), t_con0(c, "Music")));
        s.constraints.emplace_back("Phrase", av);
        env.push_back({":*:", s});
    }
    // tuplet n m music — n notes in the time of m (scales durations by m/n).
    add_mono("tuplet", t_arrow(c, t_con0(c, "Int"),
                               t_arrow(c, t_con0(c, "Int"),
                                       t_arrow(c, t_con0(c, "Music"), t_con0(c, "Music")))));
    // withInstrument inst music — assign an instrument to a phrase (Control node).
    add_mono("withInstrument", t_arrow(c, t_con0(c, "Instrument"),
                                       t_arrow(c, t_con0(c, "Music"), t_con0(c, "Music"))));
    // sfz "path" — lift a .sfz file path into a custom Instrument value.
    add_mono("sfz", t_arrow(c, t_con0(c, "Str"), t_con0(c, "Instrument")));
    // tempo bpm / velocity v — set a phrase's tempo / note velocity (Control nodes).
    add_mono("tempo", t_arrow(c, t_con0(c, "Int"),
                              t_arrow(c, t_con0(c, "Music"), t_con0(c, "Music"))));
    add_mono("velocity", t_arrow(c, t_con0(c, "Int"),
                                 t_arrow(c, t_con0(c, "Music"), t_con0(c, "Music"))));
    // `~` ties two matching phrases (notes, chords, …) into summed durations.
    // Like `:+:`, each operand is an independently-constrained Phrase; a bare
    // Pitch lifts, and the Music result lets ties chain.
    //   (~) :: Phrase t => Phrase u => t -> u -> Music
    {
        TypeId a = new_var(c); int av = c.pool[a].var;
        TypeId b = new_var(c); int bv = c.pool[b].var;
        Scheme s;
        s.vars.push_back(av);
        s.vars.push_back(bv);
        s.type = t_arrow(c, a, t_arrow(c, b, t_con0(c, "Music")));
        s.constraints.emplace_back("Phrase", av);
        s.constraints.emplace_back("Phrase", bv);
        env.push_back({"~", s});
    }
    add_mono("semitones", t_arrow(c, t_con0(c, "Pitch"), t_con0(c, "Int")));

    // list axioms — polymorphic schemes (the stdlib is built on these):
    //   null :: [a] -> Bool ; head :: [a] -> a ; tail :: [a] -> [a]
    //   cons :: a -> [a] -> [a]
    auto add_poly = [&](const char* name, int var, TypeId t) {
        Scheme s; s.vars.push_back(var); s.type = t; env.push_back({name, s});
    };
    {
        TypeId a = new_var(c); int av = c.pool[a].var;
        add_poly("null", av, t_arrow(c, t_list(c, a), t_con0(c, "Bool")));
    }
    {
        TypeId a = new_var(c); int av = c.pool[a].var;
        add_poly("head", av, t_arrow(c, t_list(c, a), a));
    }
    {
        TypeId a = new_var(c); int av = c.pool[a].var;
        add_poly("tail", av, t_arrow(c, t_list(c, a), t_list(c, a)));
    }
    {
        TypeId a = new_var(c); int av = c.pool[a].var;
        add_poly("cons", av, t_arrow(c, a, t_arrow(c, t_list(c, a), t_list(c, a))));
    }
    {   // ':' is cons as an operator
        TypeId a = new_var(c); int av = c.pool[a].var;
        add_poly(":", av, t_arrow(c, a, t_arrow(c, t_list(c, a), t_list(c, a))));
    }
    {   // '|>' pipe: forall a b. a -> (a -> b) -> b
        TypeId a = new_var(c), b = new_var(c);
        Scheme s;
        s.vars.push_back(c.pool[a].var);
        s.vars.push_back(c.pool[b].var);
        s.type = t_arrow(c, a, t_arrow(c, t_arrow(c, a, b), b));
        env.push_back({"|>", s});
    }

    // pitch projections + Music IR axioms (the music prelude builds on these)
    auto tMusic = [&]() { return t_con0(c, "Music"); };
    auto tPit   = [&]() { return t_con0(c, "Pitch"); };
    auto tInt   = [&]() { return t_con0(c, "Int"); };
    auto tBool  = [&]() { return t_con0(c, "Bool"); };
    auto tRat   = [&]() { return t_con0(c, "Rational"); };
    add_mono("makePitch", t_arrow(c, tInt(), t_arrow(c, tInt(), tPit())));
    add_mono("diatonicStep", t_arrow(c, tPit(), tInt()));
    add_mono("chromaticOf", t_arrow(c, tInt(), tInt()));
    add_mono("note", t_arrow(c, tPit(), tMusic()));
    add_mono("noteWith", t_arrow(c, tPit(), t_arrow(c, tRat(), tMusic())));
    add_mono("noteDur", t_arrow(c, tMusic(), tRat()));
    add_mono("notePitch", t_arrow(c, tMusic(), tPit()));
    add_mono("sequence", t_arrow(c, tMusic(), t_arrow(c, tMusic(), tMusic())));
    add_mono("parallel", t_arrow(c, tMusic(), t_arrow(c, tMusic(), tMusic())));
    for (const char* p : {"isNote", "isRest", "isSeq", "isPar"})
        add_mono(p, t_arrow(c, tMusic(), tBool()));
    add_mono("leftChild", t_arrow(c, tMusic(), tMusic()));
    add_mono("rightChild", t_arrow(c, tMusic(), tMusic()));

    (void)Int; (void)Bool; (void)Pitch;
}

// Infer the type of one top-level binding (function or value).
TypeId infer_binding(Checker& ck, Env& env, const Node& b) {
    Ctx& c = ck.ctx;
    std::size_t base = env.size();
    std::vector<TypeId> ptypes;
    for (int k = 0; k < b.extra; k++) {
        TypeId pv = new_var(c);
        ptypes.push_back(pv);
        Scheme s; s.type = pv;
        env.push_back({std::string(ck.ast->nodes[b.kids[k]].tok.text), s});
    }
    TypeId tbody = infer(ck, env, b.kids[b.extra]);
    env.resize(base);
    TypeId t = tbody;
    for (std::size_t k = ptypes.size(); k-- > 0;) t = t_arrow(c, ptypes[k], t);
    return t;
}

// Collect the indices (into `names`) of every top-level binding referenced in
// the subtree at `id` — the dependency edges used to order generalization.
void collect_refs(Checker& ck, NodeId id, const std::vector<std::string>& names,
                  std::vector<int>& out) {
    if (id == ast::NoNode) return;
    const Node& n = ck.ast->nodes[id];
    if (n.kind == NodeKind::Var) {
        for (std::size_t j = 0; j < names.size(); j++) {
            if (names[j] == n.tok.text) {
                bool seen = false;
                for (int o : out) if (o == static_cast<int>(j)) { seen = true; break; }
                if (!seen) out.push_back(static_cast<int>(j));
                break;
            }
        }
    }
    for (NodeId k : n.kids) collect_refs(ck, k, names, out);
}

// Tarjan SCC. Emits components in reverse-topological order (a binding's
// dependencies come out before it), which is exactly the order we generalize in.
struct Tarjan {
    const std::vector<std::vector<int>>* adj = nullptr;
    std::vector<int> index, low, stk;
    std::vector<char> on;
    int counter = 0;
    std::vector<std::vector<int>> sccs;
};
void tarjan_dfs(Tarjan& t, int v) {
    t.index[v] = t.low[v] = t.counter++;
    t.stk.push_back(v);
    t.on[v] = 1;
    for (int w : (*t.adj)[v]) {
        if (t.index[w] == -1) {
            tarjan_dfs(t, w);
            if (t.low[w] < t.low[v]) t.low[v] = t.low[w];
        } else if (t.on[w] && t.index[w] < t.low[v]) {
            t.low[v] = t.index[w];
        }
    }
    if (t.low[v] == t.index[v]) {
        std::vector<int> comp;
        for (;;) {
            int w = t.stk.back();
            t.stk.pop_back();
            t.on[w] = 0;
            comp.push_back(w);
            if (w == v) break;
        }
        t.sccs.push_back(std::move(comp));
    }
}

// Generalize the bindings at `group` (env indices) against the rest of the
// environment, then attach any still-polymorphic class constraints.
void generalize_group(Checker& ck, Env& env, const std::vector<std::size_t>& group) {
    std::vector<int> outer;
    for (std::size_t e = 0; e < env.size(); e++) {
        bool in_group = false;
        for (std::size_t s : group) if (s == e) { in_group = true; break; }
        if (in_group) continue;
        std::vector<int> fv;
        free_vars(ck.ctx, env[e].scheme.type, fv);
        for (int v : fv) {
            bool q = false;
            for (int qq : env[e].scheme.vars) if (qq == v) { q = true; break; }
            if (q) continue;
            bool seen = false;
            for (int o : outer) if (o == v) { seen = true; break; }
            if (!seen) outer.push_back(v);
        }
    }
    for (std::size_t s : group) {
        Scheme sc;
        sc.type = env[s].scheme.type;
        std::vector<int> tvs;
        free_vars(ck.ctx, sc.type, tvs);
        for (int v : tvs) {
            bool in_outer = false;
            for (int o : outer) if (o == v) { in_outer = true; break; }
            if (!in_outer) sc.vars.push_back(v);
        }
        env[s].scheme = std::move(sc);
    }
    for (std::size_t s : group) {
        Scheme& sc = env[s].scheme;
        for (auto& pc : ck.pending) {
            TypeId r = resolve(ck.ctx, pc.second);
            const TypeNode& n = ck.ctx.pool[r];
            if (!n.is_var) continue;
            bool quantified = false;
            for (int v : sc.vars) if (v == n.var) { quantified = true; break; }
            if (!quantified) continue;
            bool dup = false;
            for (auto& cc : sc.constraints)
                if (cc.first == pc.first && cc.second == n.var) { dup = true; break; }
            if (!dup) sc.constraints.emplace_back(pc.first, n.var);
        }
    }
}

// Typecheck all top-level bindings; leaves their generalized schemes in `env`.
// Bindings are grouped into mutually-recursive components (SCCs) and generalized
// in dependency order, so a polymorphic stdlib function (`map`, `length`, …) is
// generalized *before* later code uses it — and so can be used at several types.
void check_top(Checker& ck, Env& env) {
    if (ck.ast->root == ast::NoNode) return;
    const Node& prog = ck.ast->nodes[ck.ast->root];

    register_classes(ck, env);   // class methods become qualified schemes in env
    register_instances(ck);      // record which (class, type) instances exist

    std::vector<NodeId> bindings;
    for (NodeId d : prog.kids)
        if (ck.ast->nodes[d].kind == NodeKind::Binding) bindings.push_back(d);
    int N = static_cast<int>(bindings.size());

    std::vector<std::string> names(N);
    for (int i = 0; i < N; i++) names[i] = std::string(ck.ast->nodes[bindings[i]].tok.text);

    // dependency graph: i -> j if binding i's body references binding j
    std::vector<std::vector<int>> adj(N);
    for (int i = 0; i < N; i++) {
        const Node& b = ck.ast->nodes[bindings[i]];
        collect_refs(ck, b.kids[b.extra], names, adj[i]);
    }

    Tarjan t;
    t.adj = &adj;
    t.index.assign(N, -1);
    t.low.assign(N, 0);
    t.on.assign(N, 0);
    for (int i = 0; i < N; i++) if (t.index[i] == -1) tarjan_dfs(t, i);

    // process each component in dependency order
    for (const std::vector<int>& comp : t.sccs) {
        std::vector<std::size_t> group;
        for (int i : comp) {
            TypeId pv = new_var(ck.ctx);
            Scheme s; s.type = pv;
            group.push_back(env.size());
            env.push_back({names[i], s});
        }
        for (std::size_t gi = 0; gi < comp.size(); gi++) {
            TypeId ty = infer_binding(ck, env, ck.ast->nodes[bindings[comp[gi]]]);
            unify(ck, env[group[gi]].scheme.type, ty);
        }
        generalize_group(ck, env, group);
    }

    check_instances(ck, env);    // validate instance method impls (all names in scope)
    resolve_constraints(ck);     // grounded constraints must have an instance
}

// ---- rendering ----------------------------------------------------------
void render(Ctx& c, TypeId t, std::string& out, std::vector<int>& names) {
    t = resolve(c, t);
    const TypeNode& n = c.pool[t];
    if (n.is_var) {
        int idx = -1;
        for (std::size_t i = 0; i < names.size(); i++) if (names[i] == n.var) { idx = static_cast<int>(i); break; }
        if (idx < 0) { idx = static_cast<int>(names.size()); names.push_back(n.var); }
        out += "t";
        out += std::to_string(idx);
        return;
    }
    if (n.con == "->" && n.args.size() == 2) {
        TypeId l = resolve(c, n.args[0]);
        bool lparen = (c.pool[l].con == "->");
        if (lparen) out += "(";
        render(c, n.args[0], out, names);
        if (lparen) out += ")";
        out += " -> ";
        render(c, n.args[1], out, names);
        return;
    }
    if (n.con == "List" && n.args.size() == 1) {
        out += "[";
        render(c, n.args[0], out, names);
        out += "]";
        return;
    }
    out += n.con;
    for (TypeId a : n.args) { out += " "; render(c, a, out, names); }
}

// Render a scheme, prefixing any class constraints: `Transposable t0 => t0 -> ...`.
std::string render_scheme(Ctx& c, const Scheme& s) {
    std::vector<int> names;
    std::string tstr;
    render(c, s.type, tstr, names);
    if (s.constraints.empty()) return tstr;
    std::string cs;
    for (std::size_t i = 0; i < s.constraints.size(); i++) {
        if (i) cs += ", ";
        const auto& pc = s.constraints[i];
        int idx = -1;
        for (std::size_t k = 0; k < names.size(); k++)
            if (names[k] == pc.second) { idx = static_cast<int>(k); break; }
        if (idx < 0) { idx = static_cast<int>(names.size()); names.push_back(pc.second); }
        cs += pc.first + " t" + std::to_string(idx);
    }
    if (s.constraints.size() > 1) return "(" + cs + ") => " + tstr;
    return cs + " => " + tstr;
}

} // namespace

bool typecheck_program(const ast::Ast& a, std::vector<std::string>& errors) {
    Checker ck;
    ck.ast = &a;
    ck.errors = &errors;
    Env env;
    seed_builtins(ck, env);
    check_top(ck, env);
    return errors.empty();
}

std::string infer_named_type(const ast::Ast& a, std::string_view name,
                             std::vector<std::string>& errors) {
    Checker ck;
    ck.ast = &a;
    ck.errors = &errors;
    Env env;
    seed_builtins(ck, env);
    check_top(ck, env);

    Scheme s;
    if (!env_find(env, name, s)) return "";
    return render_scheme(ck.ctx, s);
}

} // namespace calliope::types
